# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Branden Espinoza
tagline: 'Branden Espinoza'
author: Branden Espinoza
name: 'Branden Espinoza
email: espin.brand@protonmail.com
description: Resource site for Branden Espinoza. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.brandenespinoza.com" # the base hostname & protocol for your site, e.g. http://example.com
rss:              RSS

# bootstrap: use the remote theme for the site itself
# remote_theme: sighingnow/jekyll-gitbook
remote_theme: CloudCannon/edition-jekyll-template




# ----
# Site


google_analytics_key:
show_full_navigation: true

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Product documentation template for Jekyll.
author:
  name:
  email:
  twitter: brandenespinoza
social:
  name: Branden Espinoza
  links:
    - https://github.com/brandenespinoza

# -----
# Build

timezone: Etc/UTC

permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  docs:
    title: Documentation
    permalink: /:path/
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "docs"
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
      _options:
        content:
          width: 800
          height: 2000
  -
    scope:
      path: ""
      type: "posts"
    values:
      _comments:
        type: Marks the impact of this release

# -----------
# CloudCannon

types:
  - minor
  - major





# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
